### PR TITLE
Marking pcs as closed

### LINKED ISSUE #66: Mark PCs as "broken"
Should have an option to mark PCs as broken, add this to PCInfo maybe?

### PR DESCRIPTION
**Pull request by devr07**
Closes #66 

This PR creates implements rendering logic and a PCStatus enum instead of an isOccupied boolean, as well as a button to mark a PC as closed.

This PR also introduces a button to mark a PC as executive until #84 is implemented at which point this button can be removed.

Changes per commit:

1. Introduced PCStatus enum replacing isOccupied boolean
2.  Introduced rendering for PCStatus, buttons to toggle the state, and a helper function for returning specified text based on value of PCStatus
3. Introduced the pcStatus logic to the rest of the front end code using a store that persists in local storage
4. Updated the colours
5. Updated the store usage rather than passing down values so components rerender automatically eliminating the need for a page refresh
6. Refactor the handle sign out store usage to ensure the text gets updated upon a user being signed into the PC that is already selected. Per the old main branch implementation there was a bug that when the pc that is currently selected is signed in, the check tab does not update, this alongside previous change of using store for PCStatus resolves this without the need for a page refresh
7. Linter changes
8. Prettier changes
9. Added a call to fetchActivities after sign out click to fix bug introduced when removing page refresh from sign out click. (Bug was that the activities page would not be updated so the text would still say Ended N/A)

Picture of selected PC is busy (visually the same as before)
image

Picture of selected PC is open 
image

Picture of selected PC is exec
image

Picture of selected PC is closed
image

Picture of bug in main described in 6.
image

### CODE REVIEW

**Comment by joshhwuu** [comment]
100th item!!

**Review by joshhwuu — COMMENTED** [review]
Noice

File: client/src/app/lounge/pc-info.tsx [hunk 1]
```diff
@@ -82,41 +95,79 @@ const PCInfo: React.FC<PCInfoProps> = ({ pc, isOccupied }) => {
...
-            className="h-full rounded border border-red-500 p-2 text-white hover:bg-red-500 hover:text-white"
-            onClick={handleClick}
-          >
-            Close
-          </button>
-          <div className="absolute bottom-full left-1/2 mb-2 mt-2 hidden w-32 -translate-x-1/2 transform rounded bg-gray-100 p-2 text-center text-xs text-black group-hover:block">
-            This sign out will be associated with the provided exec name.
-          </div>
-        </div>
+        {pcStatus !== PCStatus.Busy && (
```
[the remark this answers is not in the document]
Comment (devr07) [reply client/src/app/lounge/pc-info.tsx:122]: Created github issue #101 and will do so in a future pr

File: client/src/app/lounge/pc-info.tsx [hunk 2]
```diff
@@ -1,30 +1,43 @@
...
+  const handleExecClick = () => {
+    const store = useBoundStore.getState();
+    store.setPCStatus(
+      pc.pcNumber,
+      pcStatus === PCStatus.Exec ? PCStatus.Open : PCStatus.Exec,
+    );
+  };
+
+  const handleClosedClick = () => {
+    // alert("Broken Button clicked!");
```
[the remark this answers is not in the document]
Comment (devr07) [reply client/src/app/lounge/pc-info.tsx:35]: Whoops, done.

File: client/src/app/check-in/check-in.tsx [hunk 3]
```diff
@@ -60,6 +62,26 @@ const CheckIn = () => {
       alert("This student is already checked in.");
       return;
     }
+    if (
+      pcList.pcs.find(
```
[the remark this answers is not in the document]
Comment (devr07) [reply client/src/app/check-in/check-in.tsx:66]: Will refactor in future PR alongside github issue #101

File: client/src/app/check-in/check-in.tsx [hunk 4]
```diff
@@ -1,4 +1,4 @@
-import React, { useState, ChangeEvent } from "react";
+import React, { ChangeEvent, useState } from "react";
```
[the remark this answers is not in the document]
Comment (devr07) [reply client/src/app/check-in/check-in.tsx:1]: 🔥

File: client/src/app/lounge/pc-info.tsx [hunk 5]
```diff
@@ -82,41 +94,79 @@ const PCInfo: React.FC<PCInfoProps> = ({ pc, isOccupied }) => {
...
+            className={`text-1xl mb-1 ${getPCStatusMessage(
+              pcStatus,
+              "text-green-500",
+              "text-[#3A6AAC]",
+              "text-red-500",
+              "text-[#E2DC6A]",
+            )}`}
           >
-            {isOccupied ? "BUSY" : "OPEN"}
+            {getPCStatusMessage(pcStatus, "OPEN", "EXEC", "BUSY", "CLOSED")}
```
Comment (Jaden51) [inline client/src/app/lounge/pc-info.tsx:105]: Instead of having the string literals in the function you can define the enum values in typescript. 

So instead of doing 
```
export enum PCStatus {
  Open,
  ...
}
```
You can do
```
export enum PCStatus {
  Open = "OPEN",
  ...
}
```
And then in the `pc.ts` interface file, you can just return the enum status based on whatever `pcStatus` was.

File: client/src/app/lounge/pc-station.tsx [hunk 6]
```diff
@@ -73,8 +84,18 @@ const PCStation: React.FC<PCStationProps> = ({ pc, isOccupied, onClick }) => {
 
   return (
     <button
-      onClick={() => onClick(pc, timeRemaining, isOccupied)}
-      className={`flex items-center justify-center rounded-md p-4 text-xs ${isTimeUp ? "border border-white text-white" : isOccupied ? "bg-[#DD4345] text-white" : "bg-[#64CC9F] text-white"}`}
+      onClick={() => onClick(pc, timeRemaining, isOccupied, pcStatus)}
+      className={`flex items-center justify-center rounded-md p-4 text-xs ${
```
Comment (Jaden51) [inline client/src/app/lounge/pc-station.tsx:88]: I'm a little confused on what the purpose of the defining a variable `className` here is. Is it to display a different button each for each of the statues?

File: client/src/app/lounge/pc-info.tsx (hunk 5 above)
Comment (Jaden51) [reply client/src/app/lounge/pc-info.tsx:105]: Hmm, looking through the code, the `PCStatus` enum is tied into a lot of things and I think you are using the TypeScript default with the values of the enum just being integers correct? I don't _really_ like the way we pass in constant strings into the function so if my above suggestion doesn't work could you try something else?

File: client/src/app/lounge/pc-station.tsx (hunk 6 above)
Comment (devr07) [reply client/src/app/lounge/pc-station.tsx:88]: The classname is being used the same as before, just rather than adding another ternary operator to the chain I am using a helper function to (hopefully) improve readability. The purpose of setting the className in the button is to syle it which is how we are rendering the colour of the PC based on the PC status.

The getPCStatusMessage is just meant to be an easier to read switch statement/ternary operator chain operating on the pcStatus, so based on the value of pcStatus we can return a different string. So in this case we want to return different strings to stylize the button based on the value of pcStatus.

File: client/src/app/lounge/pc-info.tsx (hunk 5 above)
Comment (devr07) [reply client/src/app/lounge/pc-info.tsx:105]: You are correct that we are currently using the typescript default of the enum just being integers. I can change them to be strings as you suggested and that will work. As for the "helper" function getPCStatusMessage I can remove it and use a switch statement in https://github.com/ubcesports/lounge-hub/pull/100#discussion_r1970981643 instead if you feel that would be better since it would only be used in that one place then.

Comment (Jaden51) [reply client/src/app/lounge/pc-info.tsx:105]: Yeah I think it'd be better. Since the strings are constant there has to be way we can factor it out of the function and just rely on whatever `pcStatus` is. Thanks 😄 !

Comment (devr07) [reply client/src/app/lounge/pc-info.tsx]: Implemented, please see latest commit and resolve conversation if content with the changes made, or provide further feedback

**Review by Jaden51 — APPROVED** [review]
LGTM! Let Josh approve too before merging. Thanks 😄 !

**Review by joshhwuu — APPROVED** [review]
LGTM
